### ISSUE TITLE
Testnet deployment: Error: No postage stamp

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/gateway-proxy#55]
Starting the service without any suitable postage stamp on the bee node fails it (will work after few restarts). Most likely some timeout issue

```
time="2021-12-07T16:18:17.066Z" level="info" msg="buying new stamp"                                                                                                                                               
time="2021-12-07T16:21:02.103Z" level="error" msg="failed to refresh postage stamp Wait until stamp usable timeout has been reached" stack="Error: Wait until stamp usable timeout has been reached\n    at Timeo 
time="2021-12-07T16:21:02.107Z" level="info" msg="[HPM] Proxy created: /  -> <CENSORED>"                                                                               
time="2021-12-07T16:21:02.108Z" level="info" msg="[HPM] Proxy rewrite rule created: "/readiness" ~> "/""                                                                                                          
time="2021-12-07T16:21:02.108Z" level="info" msg="[HPM] Proxy created: /  -> <CENSORED>"                                                                               
/usr/src/app/dist/stamps.js:119                                                                                                                                                                                   
        throw new Error('No postage stamp');                                                                                                                                                                      
              ^                                                                                                                                                                                                   
Error: No postage stamp                                                                                                                                                                                           
    at StampsManager.get postageStamp [as postageStamp] (/usr/src/app/dist/stamps.js:119:15)                                                                                                                      
    at createApp (/usr/src/app/dist/server.js:43:107)                                                                                                                                                             
    at /usr/src/app/dist/index.js:30:42                                                                                                                                                                           
    at Generator.next (<anonymous>)                                                                                                                                                                               
    at fulfilled (/usr/src/app/dist/index.js:6:58)
```

**Comment by Cafe137** [comment]
`waitForUsable` timeout no longer crashes the app, and next interval will retry purchase

```
time="2022-10-04T19:27:25.683Z" level="info" msg="starting postage stamp manager"
time="2022-10-04T19:27:25.683Z" level="info" msg="checking postage stamps"
time="2022-10-04T19:27:25.699Z" level="debug" msg="retrieved stamps"
time="2022-10-04T19:27:25.700Z" level="info" msg="buying new stamp"
time="2022-10-04T19:27:31.749Z" level="error" msg="failed to buy postage stamp Timeout on waiting for postage stamp to become usable" stack="Error: Timeout on waiting for postage stamp to become usable\n    at BeeDebug.<anonymous> (/Users/aron/Code/gateway-proxy/node_modules/@ethersphere/bee-js/dist/cjs/bee-debug.js:632:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/aron/Code/gateway-proxy/node_modules/@ethersphere/bee-js/dist/cjs/bee-debug.js:28:58)"
time="2022-10-04T19:28:31.751Z" level="info" msg="checking postage stamps"
time="2022-10-04T19:28:31.763Z" level="debug" msg="retrieved stamps" 0={"batchID":"14fa2b775cc53168431ed46c8910fba3e34c7dc1a35135549c353e744016154b","usable":false,"amount":"200000","depth":22,"bucketDepth":16,"utilization":0,"batchTTL":86400000}
time="2022-10-04T19:28:31.763Z" level="info" msg="buying new stamp"
```
